# This workflow will install Python dependencies, run tests and lint with a variety of Python versions (currently only Python 3.7)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#description: 'Generates pyfalco build, runs tests on push or pull requests of master branch.'
name: 'pyfalco'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # This step checks out a copy of your repository.
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m  pip install https://sourceforge.net/projects/proper-library/files/proper_v3.2.5_python_3.x_21apr2021.zip/download
        python -m pip install pytest
        python -m pip install pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python pytest --html=report.html
